apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
data:
    cloudflare-token: ENC[AES256_GCM,data:sSJW0LynBEStGvSFx2wCvWC4xFcMp0iAm6fbuXoajQYIMBGAXPuPKMs2NkoSFBiIr9fRcSayC6Y1US1FBW/Xjy4EE8sM2Iai,iv:ejXUdYhEntJNtU89jbW946XT3eaOMenLmDIaDkL4d6Y=,tag:QSqpMzH2RzouTOZf65cAAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dkdlcW9tM3dKeDNiY1Q3
            Z3YyckpXY2J6SkpZeXhTT2tScmNVdURPSVhjCjFiNE14U1NPMVc1NXlpZldSYXF1
            aEs1MkdqVTVkb2w5VFA0Zm5hOWl1em8KLS0tIE4rYWQ4U0I4RStkcjQveWZTVHJD
            WDVzdVZNdUhvd2RsTU9Ta1JCVFB3dzQKvAvtknPNql1XHyXhTYhXCGpBAVVga1j3
            sPD87+9KTOI7WdtQ/K9nnQJMvkxYNgeqoaRgIR7k2gQWtvGKUoMklw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
    encrypted_regex: ^(data|stringData|annotations|values|)$
    lastmodified: "2026-09-23T11:58:42Z"
    mac: ENC[AES256_GCM,data:BIX+/WjWcFTh/6GQ9rtDzTFOoG+C90MdZsYdfMOYAI+OWVDb2zu/2bIhzKJOK2OhaxNP0gTTLHuFCI060EDoObQXYn4RpspXGLJci9o+CRQbvadRWhY6NUCJf9ZD0SbN/2qbsH6OZnFn8KQsdGcrn0FSbPcGP5Qgy6mXRjFkKIg=,iv:5Pu8nlM5Q2jUuln/hrHH6BBspepyevNNOTwdT1/WQEU=,tag:apuyzdOaih7Mj6JnHbey4Q==,type:str]
    version: 3.13.2
