apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: open-appsec-nginx
    namespace: appsec
spec:
    interval: 30m
    releaseName: open-appsec-nginx
    targetNamespace: appsec
    install:
        createNamespace: true
    chart:
        spec:
            chart: open-appsec-nginx-ingress
            version: '>=0.1.0' # Specify your desired chart version
            sourceRef:
                kind: HelmRepository
                name: open-appsec
                namespace: flux-system
    values:
        fullnameOverride: appsec-nx
        nameOverride: appsec-nx
        controller:
            ingressClass: appsec-nginx
            ingressClassResource:
                name: appsec-nginx
                controllerValue: k8s.io/appsec-nginx
            service:
                labels:
                    scope: public
                    test: true
                annotations:
                    lbipam.cilium.io/ips: 10.27.55.20
                spec:
                    externalTrafficPolicy: Local
                type: LoadBalancer
            replicaCount: 3
            affinity:
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                        - weight: 100
                          podAffinityTerm:
                            labelSelector:
                                matchExpressions:
                                    - key: app.kubernetes.io/name
                                      operator: In
                                      values:
                                        - open-appsec-nginx-ingress-controller
                            topologyKey: kubernetes.io/hostname
        appsec:
            # Use 'managed' if connecting to open-appsec SaaS portal
            mode: managed
            # Required if connecting to SaaS
            userEmail: ENC[AES256_GCM,data:4RC0gkqRTF9LnwZFK7an5w==,iv:FXaBhII4hbpaRstgbfWwAbCrHtJoCmGuDV7ccS9SzCk=,tag:C3W2cs7IxnU/J62lss3pEA==,type:str]
            # Provided by open-appsec portal if using managed mode
            agentToken: ENC[AES256_GCM,data:Yqq0PFh7mLb9QvYItE2R7GHyu0YqahX6Yg4dcSnQKdk4rk82wIg1HAZ0CKr+T9GsDTs8X1jk4c+mT0BdBD2IscPraWAmcmykXW4r,iv:N9kTR6OR9heMRKE8LLSp2CQ4PV8LUVwgSRxrzFx1c0M=,tag:N66/4eh5t5Fi11Wo0aVR0A==,type:str]
            persistence:
                # Set to true if persistent storage is available for ML learning
                enabled: true
                storageClass:
                    name: ceph-filesystem
                    accessModes: ReadWriteMany
                learning:
                    # Set to true if persistent storage is available for ML learning
                    storageClass:
                        name: ceph-filesystem
                        accessModes: ReadWriteMany
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQThTMXNFM3JvSWZOa1RL
            UGxOWS9XNXFoZ1ZLOTQwb3VDRXhzU1hLTGlRCnk5RS9CZFByQ3dUUkhjaTBKZk9T
            NnFyVVJLQzVSNmFwYnRDditON0pvWkUKLS0tIFVyYzh2ZElmRktPRUR2WTZFdjU1
            SzNKaGp2bHJ0L0RXQUVSZnZQZG13WmMKHGTUzmlF7cd7GgNU9MiUUNq5TfWDZBzH
            89D1+xOu+K9OdSYXsAp2G/OWroHb3Jl1JKSkQ3sucfmwQN70Bak69Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
    encrypted_regex: ^(userEmail|agentToken)$
    lastmodified: "2026-08-26T01:13:28Z"
    mac: ENC[AES256_GCM,data:75Ptj/mdzeOCe1YLcE0211QSRlAXNKCAsbLSSji66elvPXozeTHdM+2L6REMvLqB5UOgL6UhJbY0xE1dKhbvazRZMATm8Y+z27Vyb+qAiia85o0XjHxBVIGcBJ/kOmenJTZFUi1llCZyTaL0GxfC/1DAt7UIUbGVHfGTEOR9oV8=,iv:e5s/pR133GcXlZWCS31R23SYrOghRbaXL7dzsSywUvs=,tag:XQ1PfIEWd2VHjCJZc0XU+A==,type:str]
    version: 3.13.2
