apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: open-appsec-nginx
    namespace: flux-system
spec:
    interval: 30m
    releaseName: open-appsec-nginx
    targetNamespace: appsec
    install:
        createNamespace: true
    chart:
        spec:
            chart: open-appsec-nginx-ingress
            version: '>=0.1.0' # Specify your desired chart version
            sourceRef:
                kind: HelmRepository
                name: open-appsec
                namespace: flux-system
    values:
        fullnameOverride: appsec-nx
        nameOverride: appsec-nx
        controller:
            ingressClass: appsec-nginx
            ingressClassResource:
                name: appsec-nginx
                controllerValue: k8s.io/appsec-nginx
            service:
                labels:
                    scope: public
                annotations:
                    lbipam.cilium.io/ips: 10.27.55.20
                spec:
                    externalTrafficPolicy: Local
                type: LoadBalancer
            replicaCount: 3
            affinity:
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                        - weight: 100
                          podAffinityTerm:
                            labelSelector:
                                matchExpressions:
                                    - key: app.kubernetes.io/name
                                      operator: In
                                      values:
                                        - open-appsec-nginx-ingress-controller
                            topologyKey: kubernetes.io/hostname
        appsec:
            # Use 'managed' if connecting to open-appsec SaaS portal
            mode: managed
            # Required if connecting to SaaS
            userEmail: ENC[AES256_GCM,data:d3WkX5PigJScywjrWe4e3g==,iv:3i6GFOR4dX0B6kopBTdGuKAidEwh0YU0GilXU/eaDx4=,tag:YuR6imIZvN1HgPoK51tzlQ==,type:str]
            # Provided by open-appsec portal if using managed mode
            agentToken: ENC[AES256_GCM,data:mNAl4aMHcjlvIqSxFdVCemQYdKi5z3o3FhlVozjniKUmlzzuMyTQzXPqH30kH5Y6WuGPa6NW4yqC0LhMlCaznu9nYOPYWOkVR3u8,iv:XEDTw7zcj75aOkT237x3arA4l8c67FWTkoHPeZmWmkk=,tag:xvHZ15GXxs/L92N95IHe7A==,type:str]
            persistence:
                # Set to true if persistent storage is available for ML learning
                enabled: true
                learning:
                    storageClass: ceph-filesystem
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeDYxTFh3ZGhtRzllT1NL
            OEJ4VjJPc0pMZGNFZThmK0ZZMjlDZnhlNlNjCm1QT01PSUlwMjlSb0NCK3dyZWhy
            K1RGdWY3aWZ3NWE0ak1LSkJ0YXNqMUEKLS0tIFY1N0xIVW1hRHJJcVBlS0xNbFZ0
            dHJpcmZ5VDhtZkhZL1h4enRDU2RJNFUKDIJ5P/3dEvH6UB7ppTSavo7gcSSMMjWM
            pjmSmJhr61K4WSCkz6eYEaIFM72Qg9pTwS96+hpfLdnWVLmYpoTJ1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
    encrypted_regex: ^(userEmail|agentToken)$
    lastmodified: "2026-08-25T12:00:09Z"
    mac: ENC[AES256_GCM,data:83q1eKXg5QluC65vmie09BcR6gUrMpEDYRCOMVKwiSi371N8RN2JPxxgcBCuK2SQVdUZE1RJlULYQ8EysufW0+Mf75++aYMDby7V+9fu266D7vXcoqTm6YBUwMVA6I1Ii6DJySKkY2HHsKhS2U0bQ9Og60rdqNGCI0eoVFVe0Xc=,iv:24X/cXxfxp9oysnLy3p0jOvFT0NaqhBdV1WAo7+pluo=,tag:c2aCoVcSriYSv9gwZa6/pg==,type:str]
    version: 3.13.2
