apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: open-appsec-nginx
    namespace: flux-system
spec:
    interval: 30m
    releaseName: open-appsec-nginx
    targetNamespace: appsec
    install:
        createNamespace: true
    chart:
        spec:
            chart: open-appsec-nginx-ingress
            version: '>=0.1.0' # Specify your desired chart version
            sourceRef:
                kind: HelmRepository
                name: open-appsec
                namespace: flux-system
    values:
        fullnameOverride: appsec-nx
        nameOverride: appsec-nx
        controller:
            ingressClass: appsec-nginx
            ingressClassResource:
                name: appsec-nginx
                controllerValue: k8s.io/appsec-nginx
            service:
                labels:
                    scope: public
                annotations:
                    lbipam.cilium.io/ips: 10.27.55.20
                spec:
                    externalTrafficPolicy: Local
                type: LoadBalancer
            replicaCount: 3
            affinity:
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                        - weight: 100
                          podAffinityTerm:
                            labelSelector:
                                matchExpressions:
                                    - key: app.kubernetes.io/name
                                      operator: In
                                      values:
                                        - open-appsec-nginx-ingress-controller
                            topologyKey: kubernetes.io/hostname
        appsec:
            # Use 'managed' if connecting to open-appsec SaaS portal
            mode: managed
            # Required if connecting to SaaS
            userEmail: ENC[AES256_GCM,data:ROYcktBbaCgiNHmooBpgkg==,iv:BDipfVIp6WgsGXj5v6ZClzKhdAytocHkR/S6lYfYUZ0=,tag:7eXHHjcwQilcqr5jixLnqA==,type:str]
            # Provided by open-appsec portal if using managed mode
            agentToken: ENC[AES256_GCM,data:mJ3/tWTnVw6qUKZKNr61vbFp5EgRotfisUj8PGRqBfYcMdKt64aAjGRz7Vg4z8eWDUUiidqTeNH7ikKsi5hGkdMR34XZ10rlt61d,iv:BDAvY8tvbgVGpGxiDFY1lqrb6DMXC1scZML4dcdZDvQ=,tag:BXgb26wO0+DQUqjlVGorBw==,type:str]
            persistence:
                # Set to true if persistent storage is available for ML learning
                enabled: false
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dTNiNHFWNWJTUm1wTCtz
            UjR6eFVUakduOE5mMEtuMFdWbHpYZmhaSHpZCldwTVBQcWhnNmVSN3dQQkZiUGRs
            N1c1THZyQ3RLMjhuK3psRkMxV2tuQjAKLS0tIEpDNmNsQXhsNVRETG5wUFJPRnRa
            M0NwNU5DdGNXRmJsdWtVR0NYZ0Y0Z1EKRMVDwduCO8Rg3GozQQRP1Usv5qJ9Qvls
            k+W4iosC/ydLcFFMj2zP1aBNu4it/2KuSkDQju/ynPXZQxN8sd3Zig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
    encrypted_regex: ^(userEmail|agentToken)$
    lastmodified: "2026-08-14T14:25:28Z"
    mac: ENC[AES256_GCM,data:R6Y4IyVcChQDBfucQH0Lx/tGRyNbzO0+sgkEo+SrQqofyg0TWocN2MES85IX+7mT6Retm3Yjy+ZjJbV5h/1N57+8grIIiUHo19lBEXFU024Bw5ElXAN0qDrA0UwJ7H0fgHKGjKUnrphzEqFTxoJXMi/sHs2Z7JlCRhaCpMLlMr8=,iv:noQEgNHcNf+uxgZoFir0KfQi+IPziD0AY+qydneaTj0=,tag:BHe0GXwe2OfwdmcQ6NshyQ==,type:str]
    version: 3.13.2
