apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: prometheus
  install:
      createNamespace: true
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    prometheus:
      prometheusSpec:
        replicas: 2
        podAntiAffinity: "hard"
        externalLabels:
          cluster: prod-eu1
        additionalScrapeConfigs:
          - job_name: 'calculon-external'
            static_configs:
              - targets: ['calculon.corp.oplabs.us:8082']
                labels:
                  service: calculon

