apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-appsec
  namespace: flux-system
spec:
  url: https://charts.openappsec.io
  interval: 10m
  certSecretRef:
    name: open-appsec-cert
