apiVersion: v1
kind: Secret
metadata:
    name: lubelogger-api-secret
    namespace: lubelogger
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:Yv0Ry/8c+YhACTGdLWCYYmza0Hb+wf61VjFcI9AclbP5qrX50hGMxMUQxr8=,iv:pXxowJIcVpcVk8zST6TC3kxjgh4cD9JXWOrDiPO7Z9U=,tag:upr3Teh3/kaCgJd3aIF1Iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK2ROMFZoZTNmamdMUzRs
            RGIyV2NrZ3piL1grWTNsRU1VcS91a3hxSDJZCkpWK05CMTQ1T3NTT2E1Zjdmb3Mw
            WXZKdk9EUHVXZWtad2Z6OGZwbkVMalEKLS0tIGd1S1ZwcHF1bTJwU0t6YUJKTlJv
            bFo2SnFpcWVhOTNaRk1nMzRWMWplM1EKMD35bMEFrqX4N2gLU3LJGDyA+PaxrdP+
            EXDTE/k7/D9URi0rjuY8eJbfls2L6nTh1QsDX8nekV4xt37n1C5Vrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T03:29:38Z"
    mac: ENC[AES256_GCM,data:nio0TySYEablxc0Iq3XsUIPMg2Emz8UPjU6ggv18iaZO45vkws/sAfcQrMUEkWFfgG5TRp+bxhYzTnf4DsRqLw3cjilg4Rs9GDM0qHvcY31i4jUNpOSZkqdqPLjclUm/ouy9D21q09PXRz2M6kB3YN11Nm6I8tEdUs7xFLDGg64=,iv:fAUlZGQPCJmHQPCiGWoOnwY6eQMN89LlmsMGNtvv1sU=,tag:Ah2YrO8wfDTR+L0V0aS3eg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|values|)$
    version: 3.8.1
