apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: jpdesigns
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:oBo2fqKghjYukMxmrXyag1xQXcK8QLNvNyRYXxiE/xtdOa13YCkK8D4fTzqHo74OyTZSiAEm8jFdI+1RkLiOzGCYSWtvDTmPovy1VUljitCnp3s3k/m3rWD2uuGxSur6v3u5LRVB+Adox/y9woRwMk9ypToQmWYfx42sa8dDXgMBcyp6Oex9DZsIWRwvlUeKY6pKKkAh6xgslLHiiB/Vop39vDAWKJD7JiB0CQHvAB1umJ8tODZTzZLKSR6qS0rWga71rIfHfSx9wWHKs4FKyweviWq8dcWrJ2etgxablGrgbVAAb6HRl4ZHcVUQjNtlQc4dWw==,iv:QiLUVBT0KNPJl/86CjgIQP88yEOzmRp/hqQl4m/5Wl0=,tag:4VU26VeOXHUAzzLAAfJdmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTlM5SE8rbnhVekZvZmpn
            SmQwTmRNZGdJT3pmdzBldEZ3b3VGMmhRcHlzCkthbFhUamFYMjhSNHY5bC8xRkhQ
            WWt6WU9nSUo5Y2Z6SVlEai9Lb1k2cG8KLS0tIDNtNWJCNnhNTEVXRWFSeWVwYytS
            bjZiNi9TQjVZck5ueFEweldIeVR6Y0EKxc6I4WzEKURcvdraPDGo1DkJmiCH/yr6
            044MD/3xF9fS2gADwVgPzLR9tUrSD7aFjvgejVz914zaAFOXL03L/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T03:54:05Z"
    mac: ENC[AES256_GCM,data:Jgyb42kU/7SdqbjyckiLagGB88vcU1sIY71C+02GKBzBWSN//cn0uRZ3z9C2A8D51G9kSv6cCB5Kwz4Qu9aiL26SgQiWjC0VuASsNs5kr/E3W/p6cJa5eg+W2uvJK74Y4ag1MJpExB2viZh/1MftfVyCASdXJ1pXHu6+WFJuNmk=,iv:5+yE3wsDSYFJYViCAvvHBq1Lm7T5xSDu5EAIlOuvD6g=,tag:+sAuOphDtpAThEZMv7M58Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|values|)$
    version: 3.8.1
