apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: jpdesigns
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:cbkdSgvbeTXiGGI91MFRjM5b44e1E2EobM1s6+VqLSX1ceW6Xwk8wSuxtvVBEpETDeqPvxveVET0FmUX+Mf2hAY3QR8nD65vCpQqo6avu3qxcAZh79rBJ3Gi1+PeGSry5JK+bEYAIJNk+NUA31PvRhse5M90ic4ZbU8l4p2E1xBCfQT1KeePZH9Ux4By7K/miW60GodQ3pC3wDvASpCyNV3RPMV8BTwMT6wWDrJv/YXplDQbuq0mzHCUV6dBR5mL7dy355TMtnoBr5dkeaGmeQfFE42Nmw9qAGWXB4onQi5clujuPsd+Kd5EMlkQllgf7dFNdnWZP4A=,iv:e5FPbPNEbiNiuz1JLpUQL2nE/p59DACEDE2cHVJlHjY=,tag:lFJ6sJvfZOOOtG6S0jI1CQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTV05nMkpKR0VLVG91a3hj
            bEJ2dTdrRk1OT2NtWVpBcU8yRWVLUXUwd2wwClNFREloK1lzaExVQ3h2bDNoMHNC
            dmh0dGN1NnZ6TXc3VVMwWFp6U2hQeHcKLS0tIERPOS90NlIyUGJ1S0JNdjN0VWVq
            Smhxc3NXeGtDbWpzcXphMHFsY0VISlkK2boqaoJiLOfiCSkRJoT1TDF518dSV79q
            mficTJ59DRuVJ9lESWzCaNaedycKqN7cvEoFXtt9wUNaAOYx7L2L4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T03:40:37Z"
    mac: ENC[AES256_GCM,data:amncd0xsSCIbkWN4bSqvyrhxBvm6V0nFcJY6WiSlsnlteuaJu6BwpJUVijvThNzdfElOXCjw7lAsIR1RcUKjxD/dgZwiZCf3wUNLiwyVdW4LpveOtVrXZd2ewk8m8BD+VgXlj0ZuhLr6974j2CMpdXUUXMwAjzbYZTeUTjw6/ZE=,iv:Ilc+OnZsXwVh/mZxK9yRhJB0lDbi5BJJi5UdJRZc9RY=,tag:bsQ43m9Ik06+qS7fM9spiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|values|)$
    version: 3.8.1
