apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: jpdesigns
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:eSkbNdBexNyh+dwLBCSSpdEQlJAYFZFSUHmEYk9BqLGm68frQEGU/ReTQOWv8tpvnGjihqTyUYUSepm6Y17JOuNO/lrziZJPtSDX+SwLs9innQYuHfDi5DUQ2LW6WO4Dsqm6IKldBAbOjMQ9lOx+93pYfJbKOElyQBVQANlAANNpkZWMh0IVzw==,iv:KWJZ6Mn9/hsGLrWOUovhP3D2UjHY5awF/xZdWHtTvis=,tag:LhBy47i3DDt6ysn7NzUejA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeG96WC9NWlRCRC9NVlZV
            K2dGWmIzcjVmeWhvUGdKME5WUml3R0d6MlVVCnZmNjlOMlBSQ1MzajhKN2l0TFNJ
            S25MVW9ZdUtBVDIrZThQRHU2ci9ZblkKLS0tIFZ5dWVlSmFPOVRhSUo2TzhFTmlQ
            b0FXQ216N3JqSS9LdjdTUm5oaTdaRTgK5mSCCOp9xXzBQjpZfKiIkSMqhgfE5sZ+
            ZvRpWdFpSdc9NO5QwPrGd/Qia4NDEIEtHVqZCqjpjemFPn6Qb995AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T03:35:00Z"
    mac: ENC[AES256_GCM,data:4uKVeV5Av26p5dEbu5R4qm5HvlFNvOaUlNByaGqSajQAi6UQ/OGc35fBunCWbmCjsWoYqWsWly9mgsfae0AD///5Par96dJThyH84lPP8YC325cU/IyF+YCVk/HewUTc6zNsnCr3I7YZdEQsaHl80qbjC4iePzUK1iawBX/E0OE=,iv:3ChUtZxJSUxmlJmIqeQOD6d2NenFoiLMu1zuDrx6M1Q=,tag:LVzSpex9vJh1vHRK5WF8+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|values|)$
    version: 3.8.1
