apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: authentik-db-secret
  namespace: authentik
spec:
  vaultAuthRef: authentik-kubernetes-auth
  mount: database
  path: creds/authentik_db_rw
  destination:
    create: true
    name: authentik-db-secret
    type: Opaque
    transformation:
      templates:
        url:
          text: |
            {{- $host := "10.27.16.130:5432" -}}
            {{- printf "postgresql://%s:%s@%s/authentik_db?sslmode=prefer" (get .Secrets "username") (get .Secrets "password") $host -}}
        connstring:
          text: |
            {{- $host := "10.27.16.130:5432" -}}
            {{- printf "Host=%s;Username=%s;Password=%s;Database=authentik_db" $host (get .Secrets "username") (get .Secrets "password") -}}
  rolloutRestartTargets:
    - kind: Deployment
      name: authentik-server
